/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static Model.DAO.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Edoua
 */
public class EditEmployeesProfile extends javax.swing.JPanel
{
    private String email;
    private FrameEmployee eFrame;
    /**
     * Creates new form EditEmployeesProfile
     */
    public EditEmployeesProfile(String email, FrameEmployee eFrame)
    {
        this.eFrame = eFrame;
        this.email = email;
        initComponents();
        //buildPanel();
        setVisible(true);
    }

    private void buildPanel()
    {
        jLabel1.setText(email);
        try
        {
            String[]ageselector = new String[88];
            for(int i=13 ; i <= 100 ; i++)
            {
                ageselector[i-13] = "" + i;
            }
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(ageselector));  
            jComboBox1.setSelectedIndex(getEmployeeAge(email)-13);
            System.out.println(" zdzdzdzdzd");
            jTextField1.setText(getEmployeeFirstName(email));

            jTextField2.setText(getEmployeeAddress(email));

            jTextField3.setText(getEmployeePhone(email));

           jTextField4.setText("");
           //jTextField.set

            jTextField6.setText(getEmployeeName(email));

        } catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }

    }
    
    public void setEmail(String email)
    {
        this.email = email;
        buildPanel();
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(53, 63, 74));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        panel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        jLabel1.setText("jLabel1");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jTextField1.setText("Firstname");
        panel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 81, -1));

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField6ActionPerformed(evt);
            }
        });
        panel.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 81, -1));

        jLabel5.setText("Address");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jTextField2.setText("Address");
        panel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jLabel4.setText("Phone");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, -1, -1));

        jTextField3.setText("Phone");
        panel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 360, 65, -1));

        jLabel2.setText("Age");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLabel3.setText("Password");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, -1, -1));

        jTextField4.setText("Password");
        panel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 65, -1));

        jButton1.setText("Edit profile");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, -1, -1));

        add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed

        //EmployeePanel wind = new EmployeePanel(email);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField6ActionPerformed
    {//GEN-HEADEREND:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed

        try
        {
            if(!"".equals(jTextField4.getText()))
            {
                EditEmployee(email,jTextField1.getText(),jTextField6.getText(),jTextField2.getText(),jTextField3.getText() ,jComboBox1.getSelectedIndex()+13,jTextField4.getText());
                eFrame.setEmployee(getEmployee(email));
            }
            else
            {
                EditEmployee(email,jTextField1.getText(),jTextField6.getText(),jTextField2.getText(),jTextField3.getText() ,jComboBox1.getSelectedIndex()+13,getEmployeePassword(email));
                eFrame.setEmployee(getEmployee(email));
            }

        }catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }

        //EmployeePanel wind = new EmployeePanel(email);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
