/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.DAO;
import static Model.DAO.getCol;
import static Model.DAO.getLines;
import static Model.DAO.productAddStock;
import static Model.DAO.productDelete;
import static Model.DAO.selectAllProducts;
import Model.Product;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author Edoua
 */
public class EmployeesPanel extends javax.swing.JPanel
{
       private ArrayList<Product> allProductsList;
       private DefaultTableModel tableModel;
       private String currentName;
       private int quantity;
       
    /**
     * Creates new form EmployeesPanel
     */
    public EmployeesPanel()
    {
        initComponents();
        
    }
  public void buildPanel() throws Exception
    {
       
        
        allProductsList = selectAllProducts();
        String [] colNames = getCol("Product");
        String [][] data = getLines("Product");
        
     
        
        tableModel =  (DefaultTableModel) jTable1.getModel();
        
        
        tableModel.setDataVector(data, colNames);

        jTable1.getSelectionModel().addListSelectionListener(new EmployeesPanel.TableListener());
        
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(100);
        columnModel.getColumn(1).setPreferredWidth(50);
        columnModel.getColumn(2).setPreferredWidth(150);
        columnModel.getColumn(3).setPreferredWidth(50);
        columnModel.getColumn(4).setPreferredWidth(50);
        
       
        setTableStyle(jTable1);
        
       
    }
  
   public void setTableStyle(JTable tableStyle)
    {
        JTableHeader tableHeader=tableStyle.getTableHeader();
        tableHeader.setOpaque(true);
        tableHeader.setBackground(new Color(255, 255, 255));
        tableHeader.setForeground(new Color(0, 0, 0));
        Border lineborder = BorderFactory.createLineBorder(Color.WHITE, 1); 
        Border border = BorderFactory.createRaisedSoftBevelBorder();
        Border border2 = BorderFactory.createBevelBorder(1, new Color(235,235,235), new Color(255,255,255));
        Border border3 = BorderFactory.createEtchedBorder(new Color(235,235,235), new Color(255,255,255));
        
        tableHeader.setFont(new Font("Sergoe UI", Font.PLAIN, 12));
        tableStyle.setFont(new Font("Sergeo UI", Font.PLAIN, 12));
      
       
        tableHeader.setBorder(border3);
    }
  public class TableListener implements ListSelectionListener 
    {
       
        @Override
        public void valueChanged(ListSelectionEvent e)
        {
           int viewRow = jTable1.getSelectedRow();
            currentName = (String) jTable1.getValueAt(viewRow, 0);
            quantity = Integer.parseInt((String) jTable1.getValueAt(viewRow, 4));
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        quantityRestock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        newProductImage = new javax.swing.JTextField();
        newProductStock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        newProductDescription = new javax.swing.JTextArea();
        newProductPrice = new javax.swing.JTextField();
        newProductName = new javax.swing.JTextField();
        newProductCategory = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(53, 63, 74));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Image file");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 560, 70, 30));

        jPanel3.setBackground(new java.awt.Color(23, 35, 55));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jPanel3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel3MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Product");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 110, 30));

        jPanel5.setBackground(new java.awt.Color(23, 35, 55));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                jPanel5MouseMoved(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jPanel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel5MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Stock");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 110, 30));

        quantityRestock.setBackground(new java.awt.Color(255, 255, 255));
        quantityRestock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quantityRestock.setForeground(new java.awt.Color(51, 51, 51));
        quantityRestock.setBorder(null);
        quantityRestock.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                quantityRestockActionPerformed(evt);
            }
        });
        add(quantityRestock, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 70, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Management");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 240, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Create A New Product ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, 190, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 430));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 420, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Delete Product");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 130, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 60, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 60, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Description");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 80, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 60, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Stock");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 560, 60, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Category");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 60, 30));

        newProductImage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductImage.setBorder(null);
        newProductImage.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newProductImageActionPerformed(evt);
            }
        });
        add(newProductImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 590, 170, -1));

        newProductStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductStock.setBorder(null);
        newProductStock.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newProductStockActionPerformed(evt);
            }
        });
        add(newProductStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 590, 80, 20));

        newProductDescription.setColumns(20);
        newProductDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductDescription.setRows(5);
        newProductDescription.setBorder(null);
        jScrollPane2.setViewportView(newProductDescription);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 420, 110));

        newProductPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductPrice.setBorder(null);
        newProductPrice.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newProductPriceActionPerformed(evt);
            }
        });
        add(newProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, 80, -1));

        newProductName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductName.setBorder(null);
        newProductName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newProductNameActionPerformed(evt);
            }
        });
        add(newProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 140, -1));

        newProductCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newProductCategory.setBorder(null);
        newProductCategory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                newProductCategoryActionPerformed(evt);
            }
        });
        add(newProductCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 420, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Add Stock");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 90, 30));

        jPanel4.setBackground(new java.awt.Color(23, 35, 55));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                jPanel4MouseMoved(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                jPanel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jPanel4MousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Delete Product");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseMoved
    {//GEN-HEADEREND:event_jPanel3MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseMoved

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseEntered
    {//GEN-HEADEREND:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(39,57,82));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MouseExited
    {//GEN-HEADEREND:event_jPanel3MouseExited
        jPanel3.setBackground(new Color(23,35,55));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel3MousePressed
    {//GEN-HEADEREND:event_jPanel3MousePressed
           try
           {
               Product product = new Product(newProductName.getText(), newProductCategory.getText(), newProductDescription.getText(), Double.parseDouble(newProductPrice.getText()), Integer.parseInt(newProductStock.getText()), null, newProductImage.getText());
           
           product.insertProduct();
           
           } catch (Exception ex)
           {
               Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel5MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel5MouseMoved
    {//GEN-HEADEREND:event_jPanel5MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseMoved

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel5MouseEntered
    {//GEN-HEADEREND:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(39,57,82));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel5MouseExited
    {//GEN-HEADEREND:event_jPanel5MouseExited
        jPanel5.setBackground(new Color(23,35,55));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel5MousePressed
    {//GEN-HEADEREND:event_jPanel5MousePressed
           try
           {
               productAddStock(currentName, Integer.parseInt(quantityRestock.getText()));
           } catch (Exception ex)
           {
               Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_jPanel5MousePressed

    private void quantityRestockActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_quantityRestockActionPerformed
    {//GEN-HEADEREND:event_quantityRestockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityRestockActionPerformed

    private void newProductImageActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newProductImageActionPerformed
    {//GEN-HEADEREND:event_newProductImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductImageActionPerformed

    private void newProductStockActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newProductStockActionPerformed
    {//GEN-HEADEREND:event_newProductStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductStockActionPerformed

    private void newProductPriceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newProductPriceActionPerformed
    {//GEN-HEADEREND:event_newProductPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductPriceActionPerformed

    private void newProductNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newProductNameActionPerformed
    {//GEN-HEADEREND:event_newProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductNameActionPerformed

    private void newProductCategoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_newProductCategoryActionPerformed
    {//GEN-HEADEREND:event_newProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newProductCategoryActionPerformed

    private void jPanel4MouseMoved(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel4MouseMoved
    {//GEN-HEADEREND:event_jPanel4MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseMoved

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel4MouseEntered
    {//GEN-HEADEREND:event_jPanel4MouseEntered
       jPanel4.setBackground(new Color(39,57,82));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel4MouseExited
    {//GEN-HEADEREND:event_jPanel4MouseExited
       jPanel4.setBackground(new Color(23,35,55));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPanel4MousePressed
    {//GEN-HEADEREND:event_jPanel4MousePressed
           try
           {
               productDelete(currentName);
           } catch (Exception ex)
           {
               Logger.getLogger(EmployeesPanel.class.getName()).log(Level.SEVERE, null, ex);
           }  
          
    }//GEN-LAST:event_jPanel4MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField newProductCategory;
    private javax.swing.JTextArea newProductDescription;
    private javax.swing.JTextField newProductImage;
    private javax.swing.JTextField newProductName;
    private javax.swing.JTextField newProductPrice;
    private javax.swing.JTextField newProductStock;
    private javax.swing.JTextField quantityRestock;
    // End of variables declaration//GEN-END:variables
}
