/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
 //import org.jfree.chart.ChartPanel;

/**
 *
 * @author dwans
 */
public class StatPanel extends javax.swing.JPanel
{

    /**
     * Creates new form StatPanel
     */
    public StatPanel()
    {
        initComponents();
    }
    
    public void buildChart()
    {
        //JFreeChart chart = ChartFactory.create
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        panelGraph = new javax.swing.JPanel();

        setBackground(new java.awt.Color(53, 63, 74));
        setMinimumSize(new java.awt.Dimension(1130, 650));
        setPreferredSize(new java.awt.Dimension(1130, 650));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("je te jure j'ai fait la page statistics");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, -1, -1));
        add(panelGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 690, 200));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelGraph;
    // End of variables declaration//GEN-END:variables
}
